# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(1022, 800)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog.setMouseTracking(False)
        Dialog.setAcceptDrops(False)
        Dialog.setStyleSheet("background-image: url(:/images/test1.jpg);")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.horizontalScrollBar = QtWidgets.QScrollBar(Dialog)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(180, 641, 715, 20))
        self.horizontalScrollBar.setStyleSheet("color: rgb(85, 255, 0);")
        self.horizontalScrollBar.setMaximum(100)
        self.horizontalScrollBar.setSliderPosition(0)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 50, 258, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setStyleSheet("background-image: url(:/images/control.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser.setStyleSheet("background-image: url(:/images/control.jpg);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 677, 717, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(100)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.stop.setStyleSheet("color: rgb(255, 10, 55);\n"
"background-color: rgb(255, 8, 45);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon)
        self.stop.setCheckable(False)
        self.stop.setAutoRepeat(False)
        self.stop.setAutoExclusive(False)
        self.stop.setDefault(False)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.play = QtWidgets.QPushButton(self.layoutWidget1)
        self.play.setStyleSheet("color: rgb(90, 255, 117);\n"
"background-color: rgb(85, 170, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/play.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon1)
        self.play.setDefault(False)
        self.play.setFlat(False)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.pause = QtWidgets.QPushButton(self.layoutWidget1)
        self.pause.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pause.setMouseTracking(False)
        self.pause.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pause.setAcceptDrops(False)
        self.pause.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 65, 157);")
        self.pause.setInputMethodHints(QtCore.Qt.ImhNone)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/pause.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon2)
        self.pause.setCheckable(False)
        self.pause.setAutoDefault(True)
        self.pause.setDefault(False)
        self.pause.setFlat(False)
        self.pause.setObjectName("pause")
        self.horizontalLayout.addWidget(self.pause)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(300)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slow = QtWidgets.QPushButton(self.layoutWidget1)
        self.slow.setStyleSheet("background-image: url(:/images/slow.jpg);")
        self.slow.setText("")
        self.slow.setObjectName("slow")
        self.horizontalLayout_3.addWidget(self.slow)
        self.quick = QtWidgets.QPushButton(self.layoutWidget1)
        self.quick.setStyleSheet("background-image: url(:/images/quick.jpg);")
        self.quick.setText("")
        self.quick.setObjectName("quick")
        self.horizontalLayout_3.addWidget(self.quick)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setStyleSheet("background-image: url(:/F:/PyQtGUI/back.jpg);\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setMaximum(200)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(700, 130, 303, 481))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(30)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.add = QtWidgets.QPushButton(self.layoutWidget2)
        self.add.setStyleSheet("color: rgb(170, 85, 127);")
        self.add.setObjectName("add")
        self.horizontalLayout_7.addWidget(self.add)
        self.open = QtWidgets.QPushButton(self.layoutWidget2)
        self.open.setStyleSheet("color: rgb(170, 85, 255);")
        self.open.setObjectName("open")
        self.horizontalLayout_7.addWidget(self.open)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(50)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget.setStyleSheet("color: rgb(255, 0, 0);")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_5.addWidget(self.listWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_5.setStyleSheet("color: rgb(85, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_6.setStyleSheet("color: rgb(85, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.listWidget_2 = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_2.setStyleSheet("color: rgb(85, 255, 255);")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_7.addWidget(self.listWidget_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.horizontalScrollBar.raise_()
        self.label_3.setBuddy(self.spinBox)

        self.retranslateUi(Dialog)
        self.horizontalSlider.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.pushButton_3.clicked.connect(self.listWidget.close)
        self.pushButton_4.clicked.connect(self.listWidget.show)
        self.pushButton_5.clicked.connect(self.listWidget_2.close)
        self.pushButton_6.clicked.connect(self.listWidget_2.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pause, self.stop)
        Dialog.setTabOrder(self.stop, self.spinBox)
        Dialog.setTabOrder(self.spinBox, self.horizontalSlider)
        Dialog.setTabOrder(self.horizontalSlider, self.textBrowser)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "              图片"))
        self.label_2.setText(_translate("Dialog", "              歌词"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.stop.setText(_translate("Dialog", "停止"))
        self.play.setText(_translate("Dialog", "播放"))
        self.pause.setText(_translate("Dialog", "暂停"))
        self.label_3.setText(_translate("Dialog", "声音："))
        self.add.setText(_translate("Dialog", "创建"))
        self.open.setText(_translate("Dialog", "添加"))
        self.pushButton.setText(_translate("Dialog", "乐器"))
        self.pushButton_3.setText(_translate("Dialog", "隐藏"))
        self.pushButton_4.setText(_translate("Dialog", "显示"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Dialog", "1"))
        item = self.listWidget.item(1)
        item.setText(_translate("Dialog", "2"))
        item = self.listWidget.item(2)
        item.setText(_translate("Dialog", "3"))
        item = self.listWidget.item(3)
        item.setText(_translate("Dialog", "4"))
        item = self.listWidget.item(4)
        item.setText(_translate("Dialog", "5"))
        item = self.listWidget.item(5)
        item.setText(_translate("Dialog", "6"))
        item = self.listWidget.item(6)
        item.setText(_translate("Dialog", "7"))
        item = self.listWidget.item(7)
        item.setText(_translate("Dialog", "8"))
        item = self.listWidget.item(8)
        item.setText(_translate("Dialog", "9"))
        item = self.listWidget.item(9)
        item.setText(_translate("Dialog", "10"))
        item = self.listWidget.item(10)
        item.setText(_translate("Dialog", "11"))
        item = self.listWidget.item(11)
        item.setText(_translate("Dialog", "12"))
        item = self.listWidget.item(12)
        item.setText(_translate("Dialog", "13"))
        item = self.listWidget.item(13)
        item.setText(_translate("Dialog", "14"))
        item = self.listWidget.item(14)
        item.setText(_translate("Dialog", "15"))
        item = self.listWidget.item(15)
        item.setText(_translate("Dialog", "16"))
        item = self.listWidget.item(16)
        item.setText(_translate("Dialog", "17"))
        item = self.listWidget.item(17)
        item.setText(_translate("Dialog", "18"))
        item = self.listWidget.item(18)
        item.setText(_translate("Dialog", "19"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("Dialog", "音乐"))
        self.pushButton_5.setText(_translate("Dialog", "隐藏"))
        self.pushButton_6.setText(_translate("Dialog", "显示"))
        self.listWidget_2.setSortingEnabled(False)
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Dialog", "1"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("Dialog", "2"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("Dialog", "3"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("Dialog", "4"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("Dialog", "5"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("Dialog", "6"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("Dialog", "7"))
        item = self.listWidget_2.item(7)
        item.setText(_translate("Dialog", "8"))
        item = self.listWidget_2.item(8)
        item.setText(_translate("Dialog", "9"))
        item = self.listWidget_2.item(9)
        item.setText(_translate("Dialog", "10"))
        item = self.listWidget_2.item(10)
        item.setText(_translate("Dialog", "11"))
        item = self.listWidget_2.item(11)
        item.setText(_translate("Dialog", "12"))
        item = self.listWidget_2.item(12)
        item.setText(_translate("Dialog", "13"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)

import fuck_rc
